%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(responseTime_thrift).
-behaviour(thrift_service).


-include("responseTime_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% peak_response_time_offered(This, Client, Server, _service, _when, Rule)
function_info('peak_response_time_offered', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {struct, {'api_types', 'serviceId'}}},
          {4, {struct, {'api_types', 'timeStamp'}}},
          {5, string}]}
;
function_info('peak_response_time_offered', reply_type) ->
  oneway_void;
function_info('peak_response_time_offered', exceptions) ->
  {struct, []}
;
% average_response_time_offered(This, Server, _service, _when, Rule)
function_info('average_response_time_offered', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'api_types', 'serviceId'}}},
          {3, {struct, {'api_types', 'timeStamp'}}},
          {4, string}]}
;
function_info('average_response_time_offered', reply_type) ->
  oneway_void;
function_info('average_response_time_offered', exceptions) ->
  {struct, []}
;
% peak_response_time_experienced(This, Client, Server, _service, _when, Rule)
function_info('peak_response_time_experienced', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, {struct, {'api_types', 'serviceId'}}},
          {4, {struct, {'api_types', 'timeStamp'}}},
          {5, string}]}
;
function_info('peak_response_time_experienced', reply_type) ->
  oneway_void;
function_info('peak_response_time_experienced', exceptions) ->
  {struct, []}
;
% average_response_time_experienced(This, Client, _service, _when, Rule)
function_info('average_response_time_experienced', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'api_types', 'serviceId'}}},
          {3, {struct, {'api_types', 'timeStamp'}}},
          {4, string}]}
;
function_info('average_response_time_experienced', reply_type) ->
  oneway_void;
function_info('average_response_time_experienced', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> no_function.

